# Generated by Django 4.0.6 on 2022-08-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
